create table if not exists db_dw_hr.clife_hr_dwm_market(
building_id                bigint               comment   '养老院楼栋ID',  
membership_adviser_id      bigint               comment    '会籍顾问id',
room_type                  int                  comment    '关注房型',
product_id                 bigint               comment    '产品id',
sub_org_id                 bigint               comment    '机构id',
sub_org_name               string               comment    '机构名称',
org_id                     bigint               comment    '集团id',
org_name                   string               comment    '集团名称',
eara_id                    int                  comment    '区域id',
area_name                  string               comment    '区域名称',
card_id                    bigint               comment     '卡id',
card_name                  string               comment     '卡名称',
deposit_amount             double        comment     '下定额',
card_pay_amount            double        comment	    '刷卡金额',
cash_pay_amount            double        comment     '现金金额',
weixin_pay_amount          double        comment     '微信支付金额',
alipay_amount              double        comment     '阿里支付金额',	
other_pay_amount           double        comment     '其他方式支付金额',
receivable_amount           double        comment  '应收金额',
received_amount             double        comment  '已收金额',
received_installment_amount double        comment  '已收分期金额',
received_occupancy_amount   double        comment  '已收占用费',
membership_amount           double        comment  '会籍费',
overdue_amount              double        comment  '滞纳金',
received_overdue_amount     double        comment  '已收滞纳金',
other_amount                double        comment  '其他费用',
manager_amount              double        comment  '管理费',
trust_amount                double        comment  '托管费', 
membership_discount_amount  double        comment  '会籍优惠价',  
card_amount                 double        comment  '卡费',
card_manager_amount         double        comment  '卡管理费',
other_transfor_to_amount   double         comment  '其他转让费' ,
transfor_to_amount         double         comment  '转让费', 
other_transfor_from_amount double         comment  '其他继承费' ,
transfor_from_amount       double         comment  '继承费',
withdraw_amount            double         comment  '退会金额', 
today_deposit_amount             double        comment  '今日下定额',
today_card_pay_amount            double        comment   '今日刷卡金额',
today_cash_pay_amount            double        comment   '今日现金金额',
today_weixin_pay_amount          double        comment   '今日微信支付金额',
today_alipay_amount              double        comment   '今日阿里支付金额',	
today_other_pay_amount           double        comment   '今日其他方式支付金额',
today_receivable_amount           double        comment  '今日应收金额',
today_received_amount             double        comment  '今日已收金额'  
)comment '华润养老营销管理轻度汇总表'
partitioned by(part_date string)
row format delimited fields terminated by '\t'
stored as parquet
;