create table if not exists db_ods_nstc.clife_nstc_ods_shop_shop ( 
     shop_id                        string               comment '店铺信息id' 
    ,shop_main                      string               comment '主营品种' 
    ,shop_user_id                   string               comment '商户ID' 
    ,shop_name                      string               comment '店铺名称' 
    ,shop_logo                      string               comment '店铺图片' 
    ,shop_background                string               comment '背景图' 
    ,shop_desc                      string               comment '店铺简介' 
    ,shop_notice                    string               comment '店铺介绍内容' 
    ,shop_type                      int                  comment '认证类型0-个人，1-企业，2-经纪人' 
    ,shop_phone                     string               comment '店铺手机号' 
    ,shop_province                  string               comment '店铺所在省' 
    ,shop_city                      string               comment '店铺所在城市' 
    ,shop_area                      string               comment '店铺所在区域' 
    ,shop_town                      string               comment '乡镇' 
    ,shop_address                   string               comment '经营地址' 
    ,shop_sale                      int                  comment '总销量' 
    ,shop_star                      double               comment '信誉值(默认80)' 
    ,longitude                      string               comment '经度' 
    ,latitude                       string               comment '纬度' 
    ,recommend                      int                  comment '首页展示0-不展示' 
    ,hits                           int                  comment '浏览量' 
    ,shop_check                     int                  comment '审核0-审核中' 
    ,money                          double               comment '账户余额' 
    ,freeze                         double               comment '冻结金额' 
    ,all_money                      double               comment '总成交额' 
    ,bank_card                      string               comment '银行卡号' 
    ,bank_user_name                 string               comment '持卡人姓名' 
    ,bank_name                      string               comment '银行名字' 
    ,bank_address                   string               comment '开户行地址' 
    ,intro_user                     string               comment '推荐人' 
    ,ali_number                     string               comment '支付宝账号' 
    ,ali_name                       string               comment '支付宝名字' 
    ,times                          int                  comment '发货时间' 
    ,location                       int                  comment '排序' 
    ,create_id                      string               comment '操作人' 
    ,create_at                      string               comment '创建时间' 
    ,disabled                       int                  comment '是否禁用(0正常)' 
    ,del_flag                       tinyint              comment '删除标记' 
    ,batchId                        int                  comment '没有注释' 
) comment '店铺' 
partitioned by (  part_date string  ) 
row format delimited fields terminated by '\t' 
stored as parquet 
;