create table if not exists db_ods_nstc.clife_nstc_ods_goods_product ( 
     product_id                     string               comment '产品id' 
    ,batch_id                       string               comment '批次id' 
    ,sku                            string               comment 'SKU' 
    ,goods_id                       string               comment '商品ID' 
    ,product_name                   string               comment '货品名' 
    ,product_img                    string               comment '产品图片' 
    ,product_spec                   string               comment '货品规格' 
    ,product_price                  double               comment '价格' 
    ,product_post                   double               comment '期货购买价' 
    ,product_weight                 int                  comment '一包的重量' 
    ,product_stock                  int                  comment '库存' 
    ,product_buy_min                int                  comment '期货卖出一包的重量' 
    ,product_buy_max                int                  comment '期货卖出库存' 
    ,product_unit                   string               comment '计量单位' 
    ,product_loading                int                  comment '是否下架(0审核1-上架2下架' 
    ,product_default                int                  comment '是否默认(1是默认)' 
    ,loading_at                     string               comment '上架时间' 
    ,unloading__at                  string               comment '下架时间' 
    ,product_sale_num               int                  comment '销售量' 
    ,product_location               int                  comment '排序字段' 
    ,create_at                      string               comment '创建时间' 
    ,update_at                      string               comment '修改时间' 
    ,del_flag                       tinyint              comment '删除标记' 
    ,store_name                     string               comment '仓库名' 
) comment '商品产品' 
partitioned by (  part_date string  ) 
row format delimited fields terminated by '\t' 
stored as parquet 
;