create table if not exists db_ods_nstc.clife_nstc_ods_member_user ( 
     member_id                      string               comment '会员id' 
    ,member_phone                   string               comment '手机号' 
    ,member_name                    string               comment '昵称' 
    ,member_avator                  string               comment '头像' 
    ,`password`                     string               comment '密码' 
    ,token                          string               comment 'token' 
    ,`status`                       int                  comment '工行E企付状态0-未提交' 
    ,intro_user                     string               comment '推荐人' 
    ,`level`                        int                  comment '身份0-个人' 
    ,money                          double               comment '余额' 
    ,freeze                         double               comment '数字金额' 
    ,aurora_id                      string               comment '极光推送id' 
    ,create_at                      string               comment '注册时间' 
    ,update_at                      string               comment '更新时间' 
    ,unionid                        string               comment '微信unionid' 
    ,openid                         string               comment '微信openId' 
    ,xcxopenid                      string               comment '小程序openid' 
    ,wx_name                        string               comment '微信昵称' 
    ,ali_name                       string               comment '阿里名字' 
    ,ali_account                    string               comment '阿里手机号' 
    ,disabled                       tinyint              comment '是否冻结账号(0-正常' 
    ,del_flag                       tinyint              comment '删除标记' 
    ,icbc_status                    int                  comment '工行会员认证0-未认证' 
) comment '会员表' 
partitioned by (  part_date string  ) 
row format delimited fields terminated by '\t' 
stored as parquet 
;