create table if not exists db_dw_nstc.clife_nstc_dws_deal_message_info ( 
     member_id                      string               comment '会员id' 
    ,goods_class                    string               comment '种类' 
    ,start_place                    string               comment '开始地' 
    ,end_place                      string               comment '目的地' 
    ,release_day                    string               comment '发布时间' 
    ,member_name                    string               comment '昵称' 
    ,purchase_cnt                   bigint               comment '采购信息数量' 
    ,suppery_cnt                    bigint               comment '供应信息数量' 
    ,rent_cnt                       bigint               comment '车找苗信息数量' 
    ,lease_cnt                      bigint               comment '苗找车信息数量' 
    ,purchase_release_cnt           bigint               comment '采购信息发布中数量' 
    ,suppery_release_cnt            bigint               comment '供应信息发布中数量' 
    ,rent_release_cnt               bigint               comment '车找苗信息发布中数量' 
    ,lease_release_cnt              bigint               comment '苗找车信息发布中数量' 
    ,purchase_finish_cnt            bigint               comment '采购信息已结束数量' 
    ,suppery_finish_cnt             bigint               comment '供应信息已结束数量' 
    ,rent_finish_cnt                bigint               comment '车找苗信息已结束数量' 
    ,lease_finish_cnt               bigint               comment '苗找车信息已结束数量' 
    ,purchase_return_cnt            bigint               comment '采购信息被驳回数量' 
    ,suppery_return_cnt             bigint               comment '供应信息被驳回数量' 
    ,rent_return_cnt                bigint               comment '车找苗信息被驳回数量' 
    ,lease_return_cnt               bigint               comment '苗找车信息被驳回数量' 
    ,purchase_scan_num              bigint               comment '采购信息浏览量' 
    ,suppery_scan_num               bigint               comment '供应信息浏览量' 
    ,rent_scan_num                  bigint               comment '车找苗信息浏览量' 
    ,lease_scan_num                 bigint               comment '苗找车信息浏览量' 
) comment '买卖信息明细汇聚表dws' 
partitioned by (  part_date string  ) 
row format delimited fields terminated by '\t' 
stored as parquet 
;