create table if not exists db_dw_nstc.clife_nstc_dim_goods_goods ( 
     goods_id                       string               comment '商品id' 
    ,shop_id                        string               comment '店铺id' 
    ,shop_name                      string               comment '店铺名称' 
    ,goods_name                     string               comment '商品名称' 
    ,goods_title                    string               comment '商品标题' 
    ,class_id                       string               comment '商品分类' 
    ,class_name                     string               comment '分类名称' 
    ,parent_id                      bigint               comment '父级ID' 
    ,class_level                    tinyint              comment '类型等级(0-大类' 
    ,type_id                        string               comment '商品类型' 
    ,type_name                      string               comment '类型名称' 
    ,goods_img                      string               comment '商品主图' 
    ,goods_note                     int                  comment '0-农资商品' 
    ,goods_prop                     string               comment '商品等级' 
    ,goods_spec                     string               comment '规格详情' 
    ,goods_param                    string               comment '参数详情' 
    ,has_spec                       int                  comment '启用规格' 
    ,goods_unit                     string               comment '计量单位' 
    ,goods_loading                  int                  comment '是否下架(0-待上架，1-上架' 
    ,recommend                      string               comment '商品推荐0-不推荐' 
    ,recom_xq                       int                  comment '邮费' 
    ,recom_gwc                      int                  comment '挂牌0-普通' 
    ,brand_id                       string               comment '商品品牌' 
    ,brand_name                     string               comment '品牌名称' 
    ,brand_url                      string               comment '品牌网址' 
    ,create_at                      string               comment '创建时间' 
    ,update_at                      string               comment '修改时间' 
) comment '商品信息表' 
partitioned by (  part_date string  ) 
row format delimited fields terminated by '\t' 
stored as parquet 
;