create table if not exists db_dw_nstc.clife_nstc_dim_shop_shop ( 
     shop_id                        string               comment '店铺信息id' 
    ,shop_main                      string               comment '主营品种' 
    ,shop_user_id                   string               comment '商户ID' 
    ,`name`                         string               comment '商家昵称' 
    ,shop_name                      string               comment '店铺名称' 
    ,shop_logo                      string               comment '店铺图片' 
    ,shop_background                string               comment '背景图' 
    ,shop_desc                      string               comment '店铺简介' 
    ,shop_notice                    string               comment '店铺介绍内容' 
    ,shop_type                      int                  comment '认证类型0-个人，1-企业，2-经纪人' 
    ,shop_phone                     string               comment '店铺手机号' 
    ,shop_province                  string               comment '店铺所在省' 
    ,shop_city                      string               comment '店铺所在城市' 
    ,shop_area                      string               comment '店铺所在区域' 
    ,shop_town                      string               comment '乡镇' 
    ,shop_address                   string               comment '经营地址' 
    ,shop_star                      double               comment '信誉值(默认80)' 
    ,longitude                      string               comment '经度' 
    ,latitude                       string               comment '纬度' 
    ,create_id                      string               comment '操作人' 
    ,create_at                      string               comment '创建时间' 
    ,recommend                      int                  comment '首页展示' 
    ,shop_check                     int                  comment '审核状态' 
) comment '店铺维表' 
partitioned by (  part_date string  ) 
row format delimited fields terminated by '\t' 
stored as parquet 
;